/**
 * "Is this an established domain?" — a Bloom filter over the Tranco top sites (ADR-0019). PURE.
 *
 * Why it exists: in URL letters alone, a real shop's `/myaccount/login` and a phishing kit's
 * `/login.php` read the same. What separates them is that the shop's domain is years old and
 * visited by millions. Measured on the live feeds, only ~1–3% of fresh phish sit on a top-10k
 * domain, while ~16% of ordinary links do — so this prior removes a large share of the model's
 * false alarms at almost no cost in detection.
 *
 * It is a *discount*, never a pass: `local-blocklist`, `userinfo-trick`, `typosquat` and every
 * other rule still apply in full. Only the learned model and the name-based lure are softened,
 * because those are the two signals that cannot tell a popular site's login page from a kit's.
 *
 * A Bloom filter answers "definitely not in the list" or "probably in the list" (~1% false
 * positives), in a fraction of the space of the list itself. Static data, generated by
 * `scripts/model/popular.mjs`; nothing is fetched (golden rules 1 and 2).
 */

import POPULAR from './data/popular-domains.json';
import { fromBase64 } from './model/score.js';

function fnv(s, seed) {
  let h = seed >>> 0;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** Bit positions for `key` — double hashing, shared with the generator so both agree. */
export function bloomPositions(key, bits, k) {
  const h1 = fnv(key, 0x811c9dc5);
  const h2 = fnv(key, 0x01000193) | 1;
  const out = [];
  for (let i = 0; i < k; i++) out.push(((h1 + Math.imul(i, h2)) >>> 0) % bits);
  return out;
}

let filter = null;

/**
 * @param {string} registrable eTLD+1 from parse.js — never a raw host, so tenants of a hosting
 *   platform ('evil.vercel.app') can never inherit the platform's popularity.
 */
export function isEstablished(registrable) {
  if (!registrable || !POPULAR.bloom) return false;
  filter ??= fromBase64(POPULAR.bloom);
  return bloomPositions(registrable, POPULAR.bits, POPULAR.k).every(
    (p) => (filter[p >>> 3] >>> (p & 7)) & 1
  );
}
