#!/usr/bin/env node
/**
 * Build `src/engine/data/popular-domains.json`: a Bloom filter over the Tranco top N registrable
 * domains (ADR-0019). Dev-time only.
 *
 *   node scripts/model/run.mjs popular --tranco .model-data/top-1m.csv [--top 10000] [--fp 0.01]
 *
 * Hosting platforms are left out on purpose. `vercel.app` is popular; its tenants are anyone.
 * parse.js already gives each tenant its own registrable domain, and excluding the platforms
 * here means a future change there cannot quietly hand every tenant the platform's standing.
 */
import fs from 'node:fs';
import { parseUrl } from '../../src/engine/parse.js';
import { bloomPositions } from '../../src/engine/popular.js';
import TLDS from '../../src/engine/data/tlds.json';

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, all) => (a.startsWith('--') ? [...acc, [a.slice(2), all[i + 1]]] : acc), [])
);
const TOP = Number(args.top ?? 10000);
const FP = Number(args.fp ?? 0.01);
const hosting = new Set(TLDS.hostingSuffixes ?? []);

const domains = [];
const seen = new Set();
for (const line of fs.readFileSync(args.tranco ?? '.model-data/top-1m.csv', 'utf8').split('\n')) {
  if (domains.length >= TOP) break;
  const d = line.split(',')[1]?.trim();
  if (!d || hosting.has(d)) continue;
  const reg = parseUrl(`https://${d}/`)?.registrable;
  if (!reg || seen.has(reg) || hosting.has(reg)) continue;
  seen.add(reg);
  domains.push(reg);
}

// Optimal Bloom sizing: m = -n ln p / (ln 2)^2, k = (m/n) ln 2.
const bits = Math.ceil((-domains.length * Math.log(FP)) / Math.LN2 ** 2);
const k = Math.max(1, Math.round((bits / domains.length) * Math.LN2));
const bytes = new Uint8Array(Math.ceil(bits / 8));
for (const d of domains) for (const p of bloomPositions(d, bits, k)) bytes[p >>> 3] |= 1 << (p & 7);

const out = {
  $comment: [
    'GENERATED by scripts/model/popular.mjs from the Tranco list — do not edit (ADR-0019).',
    'A Bloom filter of established registrable domains. Softens the learned model only.',
  ],
  source: 'Tranco top sites',
  builtAt: new Date().toISOString().slice(0, 10),
  count: domains.length,
  bits,
  k,
  bloom: Buffer.from(bytes).toString('base64'),
};
fs.writeFileSync(args.out ?? 'src/engine/data/popular-domains.json', JSON.stringify(out, null, 2) + '\n');
console.log(`${domains.length} domains → ${bits} bits, k=${k}, ${(out.bloom.length / 1024).toFixed(1)}kb`);
